spring.application.name=system


spring.datasource.url=jdbc:mysql://localhost:3307/passe_digital_secretaria_da_educacao
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=Q9xL2mV8kR7pN4cT1yW6zF3aH0jU5sD8gB2eK9nM7qP4rX1vC6tY3wZ8hJ5uL0iO2pA7dS4fG9kH1mN6bV3cX8zQ5wE2rT7yU0iP4oL9kJ6hG3fD8sA1qW5eR2tY7uI0oP4aS9dF6gH1jK8lZ3xC5vB2nM7qW4eR0tY9uI6oP3aS8dF1gH5jK2lZ7xC4vB9nM6qW3eR8tY0uI5oP2aS7dF4gH9jK1lZ6xC3vB8nM5qW0eR7tY2uI9oP6aS3dF8gH1jK4lZ5xC2vB7nM0qW9eR6qadg123uI8oP1aS4dF7gH2jK5lZ0xC9vB6nM3qW8eR1tY4uI7oP2aS5dF0gH9jK6



# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kaua.santanaj@gmail.com
spring.mail.password=fabd hnqm bgzz dgux

# SMTP
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Opcional
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
